import type { LearningSection } from '../types'

export const LEARNING_SECTIONS: LearningSection[] = [
  {
    id: 'letters',
    title: 'Letters',
    subtitle: 'Learn letter shapes and sounds.',
    image: 'assets/sections/letters.webp',
    color: '#ff986f',
    eyebrow: 'Earliest Reader',
    pocket: '5 letter-sounds',
    helper: 'Hear the sound, see the shape, then match.',
    cta: 'Start letters',
    imagePrompt: 'Text-free premium children’s storybook illustration of a friendly panda with blank wooden blocks and blank alphabet-card shapes in a sunny meadow. Gentle watercolor and gouache textures, warm cozy lighting, simple uncluttered app tile composition, no text, no letters, no numbers, no logo, no watermark.',
  },
  {
    id: 'sounds',
    title: 'Sounds',
    subtitle: 'Hear the sounds that make words.',
    image: 'assets/sections/sounds.webp',
    color: '#c9f4df',
    eyebrow: 'Earliest Reader',
    pocket: '5 reading sounds',
    helper: 'Listen first, then choose between two sounds.',
    cta: 'Start sounds',
    imagePrompt: 'Text-free premium children’s storybook illustration of a friendly panda listening to birds, bells, and soft colorful sound waves in a sunny garden. Gentle watercolor and gouache textures, warm cozy lighting, simple uncluttered app tile composition, no text, no letters, no numbers, no logo, no watermark.',
  },
  {
    id: 'words',
    title: 'Words',
    subtitle: 'Read words with pictures.',
    image: 'assets/sections/words.webp',
    color: '#ffd8c5',
    eyebrow: 'Growing Reader',
    pocket: '4 tiny words',
    helper: 'Picture, audio, word, then a quick check.',
    cta: 'Read words',
    imagePrompt: 'Text-free premium children’s storybook illustration of a friendly panda at a cozy table with picture-only cards showing simple objects like apple, cat, sun, and tree. Gentle watercolor and gouache textures, warm cozy lighting, simple uncluttered app tile composition, no text, no letters, no numbers, no logo, no watermark.',
  },
  {
    id: 'stories',
    title: 'Stories',
    subtitle: 'Read little books.',
    image: 'assets/sections/stories.webp',
    color: '#cfeefe',
    eyebrow: 'Growing Reader',
    pocket: '1 small book',
    helper: 'Turn pages with audio help and big words.',
    cta: 'Pick a book',
    imagePrompt: 'Text-free premium children’s storybook illustration of a friendly panda opening a glowing storybook in a cozy reading nook, with tiny castles, forests, and clouds rising from blank pages. Gentle watercolor and gouache textures, warm cozy lighting, simple uncluttered app tile composition, no text, no letters, no numbers, no logo, no watermark.',
  },
  {
    id: 'math',
    title: 'Math',
    subtitle: 'Count, add, and subtract.',
    image: 'assets/sections/math.webp',
    color: '#e6ddff',
    eyebrow: 'Number play',
    pocket: '5 questions',
    helper: 'Count objects first, then tap one answer.',
    cta: 'Start math',
    imagePrompt: 'Text-free premium children’s storybook illustration of a friendly panda counting apples, buttons, and small wooden counters in two neat groups on a soft mat. Gentle watercolor and gouache textures, warm cozy lighting, simple uncluttered app tile composition, no text, no letters, no numbers, no equations, no logo, no watermark.',
  },
  {
    id: 'chinese',
    title: 'Chinese',
    subtitle: 'Learn simple Chinese characters.',
    image: 'assets/sections/chinese.webp',
    color: '#f26d9d',
    eyebrow: 'Chunky Chinese',
    pocket: '5 characters',
    helper: 'Hear it, see it, then review with cards.',
    cta: 'Start Chinese',
    imagePrompt: 'Text-free premium children’s storybook illustration of a friendly panda holding a calligraphy brush beside bamboo, lanterns, ink stone, and blank practice cards. Gentle watercolor and gouache textures, warm cozy lighting, simple uncluttered app tile composition, no text, no letters, no Chinese characters, no numbers, no logo, no watermark.',
  },
]
